攻击力: 攻击力
PVP攻击力: pvp攻击力
PVE攻击力: pve攻击力
防御力: 防御力
PVP防御力: pvp防御力
PVE防御力: pve防御力
闪避几率: 闪避几率
命中几率: 命中几率
穿透几率: 穿透几率
暴击几率: 暴击几率
暴击伤害: 暴击伤害
生命偷取: 生命偷取
攻击回血: 攻击回血
点燃几率: 点燃几率
点燃伤害: 点燃伤害
闪电几率: 闪电几率
闪电伤害: 闪电伤害
爆炸几率: 爆炸几率
爆炸伤害: 爆炸伤害
凋零几率: 凋零几率
凋零伤害: 凋零伤害
施毒几率: 施毒几率
中毒伤害: 中毒伤害
减速几率: 减速几率
格挡几率: 格挡几率
格挡伤害: 格挡伤害
反弹几率: 反弹几率
反弹伤害: 反弹伤害
生命值: 生命值
生命回复: 生命回复
移动速度: 移动速度
经验加成: 经验加成
分隔符号: ":"